### PR TITLE
Add dedicated 404 page

### PR DESCRIPTION
**Pull request by stefnotch**
This adds a 404 page which should automatically redirect the user.

With this, we can get rid of the `@powershell copy \"./dist/index.html\" \"./dist/404.html\"` command.

### CODE REVIEW

**Comment by mgatelabs** [comment]
This is in the dev branch, just haven't pushed it to pages yet.

**Comment by stefnotch** [comment]
The dev branch that I can see on Github just has the powershell command. Which won't work on systems that don't have a powershell installed.
Hence, I think it would be more elegant to put a `404.html`, which always redirects to the proper page, into the `public` folder.

**Comment by mgatelabs** [comment]
Does it handle routes?  Making a copy of the index as 404 was the suggested solution for handling routes.  Now if there is a npm tool that would make the copy that would also work.

**Comment by stefnotch** [comment]
Oh, *now* I understand. The 404.html fallback is being used, because Github pages doesn't support any of the usual URL-rewriting. And Angular doesn't seem to support generation multiple `.html` files, one per page.

In that case, the copying approach really is a decent option. Another option would be to use hash-bang URLs. https://angular.io/api/common/HashLocationStrategy

**Comment by stefnotch** [comment]
After some more searching, I found another option. Pre-rendering pages: https://angular.io/guide/prerendering
If done properly, Google would be able to index every single puzzle-page. Which would be pretty neat in its own right.

**Comment by mgatelabs** [comment]
More ideas to think about.  But I replaced PowerShell with a NodeJS script to copy the file.

**Comment by stefnotch** [comment]
> More ideas to think about. But I replaced PowerShell with a NodeJS script to copy the file.

Thank you very much! That definitely addresses the portability part.

**Pull request closed without merging**
